### ISSUE TITLE
Enable WebUiAutomationToolKit.Extensions

### ISSUE THREAD

**Issue by marcellusfarias** [johnstimbert/AutomationToolKit#43]
I can't use this namespace from nuget. I wanted to use the method ConvertToBy.

**Comment by marcellusfarias** [comment]
Well, I just realized that it wont be able to solve my problem. I will create a method that returns all child elements for a spefic SelectorData.

**Comment by johnstimbert** [comment]
Getting all children blindly is not proper in any situation.  I would suggest having ids added or some other way to fix the target pages being selected.

**Comment by marcellusfarias** [comment]
Do you have any idea on how to work tables and iterate through rows in a proper way?
